In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree, metrics

In [2]:
import os
print(os.getcwd())

c:\Users\rodri\Documents\DS 2º ano\DDDM\AMPL

In [3]:
historical = pd.read_csv('historical.csv', header=None)
historical.head(n=5)

   0  1    2    3   4   5   6  7   8    9   10  11 12  13 14  15  16  17  18
0  70  M  109  145  34   1   1  O  71    b   a  68  M   0  B  81  ab   a   8
1  62  F   83  200  31   1   0  O  62  NaN   a  42  F   0  O  57   a  ab   4
2  73  M  120  160  29   0   1  A  66   ab  ab  40  F   1  A  62  ab   a   4
3  19  F   98  190  33   0   0  O  48    a   a  75  F   0  O  49  ab   b  11
4  41  F  122  100  28   1   0  B  35   ab   b  56  F   0  B  72  ab   b  15

In [4]:
don_genders = OneHotEncoder(categories=[['F','M']], sparse_output=False).fit_transform(historical[[1]])
don_btypes = OneHotEncoder(categories=[['A', 'B', 'AB', 'O', np.nan]], sparse_output=False).fit_transform(historical[[7]])
don_hlaB = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(historical[[9]])
don_hlaDR = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(historical[[10]])
pat_genders = OneHotEncoder(categories=[['F','M']], sparse_output=False).fit_transform(historical[[12]])
pat_btypes = OneHotEncoder(categories=[['A', 'B', 'AB', 'O', np.nan]], sparse_output=False).fit_transform(historical[[14]])
pat_hlaB = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(historical[[16]])
pat_hlaDR = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(historical[[17]])

In [5]:
donN = historical[[0,2,3,4,5,6,8]].values # numerical features
patN = historical[[11,13,15]].values # numerical features
X = np.concatenate((don_genders, don_hlaB, don_hlaDR, donN,
pat_genders, pat_hlaB, pat_hlaDR, patN), axis=1)
y = historical[[18]].values

In [6]:
model = tree.DecisionTreeRegressor(random_state=0, max_depth=4)
model = model.fit(X, y)

In [7]:
ypred = model.predict(X)
print(f"compute errors using the training set -- *** not meaningful, just out of curiosity ***")
print(f"maximum error: {metrics.max_error(y, ypred)}")
print(f"mean absolute error: {metrics.mean_absolute_error(y, ypred)}")
print(f"mean squared error in the training set: {metrics.mean_squared_error(y, ypred)}")

compute errors using the training set -- *** not meaningful, just out of curiosity ***
maximum error: 18.815344603381014
mean absolute error: 4.134172319283718
mean squared error in the training set: 28.123169917141354

In [8]:
pool = pd.read_csv('pool.csv', header=None)
don_genders = OneHotEncoder(categories=[['F','M']], sparse_output=False).fit_transform(pool[[2]])
don_btypes = OneHotEncoder(categories=[['A', 'B', 'AB', 'O', np.nan]], sparse_output=False).fit_transform(pool[[8]])
don_hlaB = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(pool[[10]])
don_hlaDR = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(pool[[11]])
pat_genders = OneHotEncoder(categories=[['F','M']], sparse_output=False).fit_transform(pool[[13]])
pat_btypes = OneHotEncoder(categories=[['A', 'B', 'AB', 'O', np.nan]], sparse_output=False).fit_transform(pool[[15]])
pat_hlaB = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(pool[[17]])
pat_hlaDR = OneHotEncoder(categories=[['a', 'b', 'ab', np.nan]], sparse_output=False).fit_transform(pool[[18]])
Xdon = np.concatenate((don_genders, don_hlaB, don_hlaDR, pool[[1,3,4,5,6,7,9]].values), axis=1)
Xpat = np.concatenate((pat_genders, pat_hlaB, pat_hlaDR, pool[[12,14,16]].values), axis=1)

In [14]:
pool.describe()

,0,1,3,4,5,6,7,9,12,14,16
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000
mean,50.500000,48.090000,93.190000,141.750000,27.74000,0.250000,0.130000,67.070000,45.16000,0.220000,69.400000
std,29.011492,16.357802,18.680566,36.744923,8.57365,0.435194,0.337998,16.680755,15.71766,0.416333,15.963975
min,1.000000,18.000000,60.000000,80.000000,12.00000,0.000000,0.000000,30.000000,18.00000,0.000000,40.000000
25%,25.750000,34.000000,79.000000,105.000000,20.75000,0.000000,0.000000,56.000000,31.75000,0.000000,56.750000
50%,50.500000,49.000000,89.000000,145.000000,28.50000,0.000000,0.000000,66.500000,46.50000,0.000000,68.000000
75%,75.250000,61.250000,110.250000,170.000000,34.00000,0.250000,0.000000,78.250000,59.00000,0.000000,83.000000
max,100.000000,76.000000,129.000000,200.000000,44.00000,1.000000,1.000000,104.000000,75.00000,1.000000,105.000000

In [13]:
don_btype = pool[[8]].values.ravel()
pat_btype = pool[[15]].values.ravel()
n_pairs = len(pool)
for i in range(n_pairs):
  X = [list(Xdon[i]) + list(Xpat[i])]
  survival = model.predict(X)[0]
  print(f"Patient {i}:", survival)

Patient 0: 3.5901639344262297
Patient 1: 8.24
Patient 2: 7.286096256684492
Patient 3: 15.889007470651014
Patient 4: 9.421296296296296
Patient 5: 18.815344603381014
Patient 6: 12.843657817109145
Patient 7: 7.286096256684492
Patient 8: 18.815344603381014
Patient 9: 3.3066666666666666
Patient 10: 7.286096256684492
Patient 11: 9.421296296296296
Patient 12: 12.843657817109145
Patient 13: 15.889007470651014
Patient 14: 4.696969696969697
Patient 15: 9.421296296296296
Patient 16: 9.421296296296296
Patient 17: 15.889007470651014
Patient 18: 7.286096256684492
Patient 19: 15.889007470651014
Patient 20: 8.24
Patient 21: 7.286096256684492
Patient 22: 15.889007470651014
Patient 23: 9.625850340136054
Patient 24: 15.889007470651014
Patient 25: 9.625850340136054
Patient 26: 8.24
Patient 27: 18.815344603381014
Patient 28: 18.815344603381014
Patient 29: 18.815344603381014
Patient 30: 7.286096256684492
Patient 31: 5.219387755102041
Patient 32: 18.815344603381014
Patient 33: 18.815344603381014
Patient 34: 5.219387755102041
Patient 35: 7.286096256684492
Patient 36: 9.421296296296296
Patient 37: 9.625850340136054
Patient 38: 15.889007470651014
Patient 39: 15.889007470651014
Patient 40: 12.843657817109145
Patient 41: 15.889007470651014
Patient 42: 9.421296296296296
Patient 43: 8.24
Patient 44: 18.815344603381014
Patient 45: 3.3066666666666666
Patient 46: 9.421296296296296
Patient 47: 15.889007470651014
Patient 48: 18.815344603381014
Patient 49: 12.843657817109145
Patient 50: 15.889007470651014
Patient 51: 3.5901639344262297
Patient 52: 5.219387755102041
Patient 53: 3.3066666666666666
Patient 54: 7.286096256684492
Patient 55: 12.843657817109145
Patient 56: 9.625850340136054
Patient 57: 7.286096256684492
Patient 58: 8.24
Patient 59: 7.286096256684492
Patient 60: 15.889007470651014
Patient 61: 8.24
Patient 62: 8.24
Patient 63: 12.843657817109145
Patient 64: 18.815344603381014
Patient 65: 12.843657817109145
Patient 66: 7.286096256684492
Patient 67: 8.24
Patient 68: 18.815344603381014
Patient 69: 8.24
Patient 70: 8.24
Patient 71: 2.854368932038835
Patient 72: 12.843657817109145
Patient 73: 9.421296296296296
Patient 74: 7.286096256684492
Patient 75: 18.815344603381014
Patient 76: 8.24
Patient 77: 9.421296296296296
Patient 78: 9.421296296296296
Patient 79: 15.889007470651014
Patient 80: 15.889007470651014
Patient 81: 15.889007470651014
Patient 82: 18.815344603381014
Patient 83: 18.815344603381014
Patient 84: 8.24
Patient 85: 15.889007470651014
Patient 86: 15.889007470651014
Patient 87: 8.24
Patient 88: 8.24
Patient 89: 15.889007470651014
Patient 90: 8.24
Patient 91: 12.843657817109145
Patient 92: 2.854368932038835
Patient 93: 9.421296296296296
Patient 94: 12.843657817109145
Patient 95: 3.5901639344262297
Patient 96: 8.24
Patient 97: 12.843657817109145
Patient 98: 18.815344603381014
Patient 99: 12.843657817109145

In [15]:
import time
from amplpy import AMPL, Environment, DataFrame

In [49]:
def compute_cycle_weight(cycle, surv):
    total = 0
    for i in range(len(cycle)):
        a = cycle[i]
        b = cycle[(i + 1) % len(cycle)]  # wrap around to make a cycle
        total += surv.get((a, b), 0)  # add weight if exists, else 0
    return total

def normalize(cycle):
    cmin = min(cycle)
    while cycle[0] != cmin:
        v = cycle.pop(0)
        cycle.append(v)


def all_cycles(cycles, path, node, tovisit, adj,K):
    for i in adj[node]:
        if i == node:
            cycle = [node]
            cycles.add(tuple(cycle))
        if i in path:
            j = path.index(i)
            cycle = path[j:]+[node]
            normalize(cycle)
            cycles.add(tuple(cycle))

        if i in tovisit:
            if K-1 > 0:
                all_cycles(cycles,path+[node],i,tovisit-set([i]),adj,K-1)
    return cycles


def get_all_cycles(adj,K):
    tovisit = set(adj.keys())
    visited = set()
    cycles = set()
    for i in tovisit:
        tmpvisit = set(tovisit)
        tmpvisit.remove(i)
        first = i
        all_cycles(cycles,[],first,tmpvisit,adj,K)
    return cycles


# def kep_cycle(adj, cycles, weights):
#     ampl = AMPL()
#     ampl.option['solver'] = 'gurobi'
#     ampl.read("KEP_MAX.mod")

#     # Pass cycles
#     ampl.set['V'] = list(adj)
#     ampl.param['m'] = len(cycles)
#     for i, c in enumerate(cycles):
#         ampl.set['CYCLE'][i] = list(c)

#     # Pass weights (i.e., total survival per cycle)
#     ampl.param['w'] = {i: weights[i] for i in range(len(weights))}

#     ampl.solve()
#     assert ampl.getValue('solve_result') == "solved"

#     z = ampl.obj['z']
#     x = ampl.var['x']
#     sol = [c for i, c in enumerate(cycles) if x[i].value() > 0.5]
#     return z.value(), sol

In [47]:
def kep_cycle(adj,cycles, weights):
    ampl = AMPL()
    ampl.option['solver'] = 'gurobi'
    ampl.read("KEP_MAX.mod")
    ampl.set['V'] = list(adj)   # vertices are keys in 'adj'
    ampl.param['m'] = len(cycles)
    ampl.param['w'] = {i: weights[i] for i in range(len(weights))}
    for i,c in enumerate(cycles):
        ampl.set['CYCLE'][i] = list(c)
   
    ampl.solve()
    assert ampl.getValue('solve_result') == "solved"

    z = ampl.obj['z']
    x = ampl.var['x']
    sol = []
    for i,c in enumerate(cycles):
        if x[i].value() > 0.5:
            sol.append(c)
    return z.value(), sol

In [50]:
threshold = 5 # patient survival time must be >= 5
compat = {
    "O":["O"],
    "A":["O","A"],
    "B":["O", "B"],
    "AB":["O", "A", "B", "AB"],
}
adj = {}
surv = {}
for j in range(n_pairs): # index for donor's pair
    adj[j] = [] # start with an empty list for each donor
    for i in range(n_pairs): # index for patient's pair
        if don_btype[j] in compat[pat_btype[i]]: # 'j' is blood-type compatible with 'i'
            X = [list(Xdon[j]) + list(Xpat[i])]
            survival = round(model.predict(X)[0],0) # predicted survival time
            if survival >= threshold: #
                adj[j].append(i)
                surv[j,i] = survival

In [42]:
print("Compatible donor-patient pairs with survival ≥ 5 years:")
for (j, i), s in surv.items():
    print(f"Donor {j} → Patient {i} : {s}")

Compatible donor-patient pairs with survival ≥ 5 years:
Donor 0 → Patient 7 : 5.0
Donor 0 → Patient 11 : 5.0
Donor 0 → Patient 12 : 5.0
Donor 0 → Patient 13 : 5.0
Donor 0 → Patient 19 : 5.0
Donor 0 → Patient 27 : 5.0
Donor 0 → Patient 28 : 5.0
Donor 0 → Patient 29 : 5.0
Donor 0 → Patient 30 : 5.0
Donor 0 → Patient 32 : 5.0
Donor 0 → Patient 33 : 5.0
Donor 0 → Patient 36 : 5.0
Donor 0 → Patient 39 : 5.0
Donor 0 → Patient 46 : 5.0
Donor 0 → Patient 49 : 5.0
Donor 0 → Patient 57 : 5.0
Donor 0 → Patient 60 : 5.0
Donor 0 → Patient 65 : 5.0
Donor 0 → Patient 72 : 5.0
Donor 0 → Patient 74 : 5.0
Donor 0 → Patient 75 : 5.0
Donor 0 → Patient 77 : 5.0
Donor 0 → Patient 80 : 5.0
Donor 0 → Patient 81 : 5.0
Donor 0 → Patient 93 : 5.0
Donor 0 → Patient 97 : 5.0
Donor 1 → Patient 0 : 8.0
Donor 1 → Patient 1 : 8.0
Donor 1 → Patient 2 : 19.0
Donor 1 → Patient 3 : 19.0
Donor 1 → Patient 4 : 19.0
Donor 1 → Patient 5 : 19.0
Donor 1 → Patient 6 : 19.0
Donor 1 → Patient 7 : 19.0
Donor 1 → Patient 8 : 19.0
Donor 1 → Patient 9 : 19.0
Donor 1 → Patient 10 : 19.0
Donor 1 → Patient 11 : 19.0
Donor 1 → Patient 12 : 19.0
Donor 1 → Patient 13 : 19.0
Donor 1 → Patient 14 : 8.0
Donor 1 → Patient 15 : 19.0
Donor 1 → Patient 16 : 19.0
Donor 1 → Patient 17 : 19.0
Donor 1 → Patient 18 : 19.0
Donor 1 → Patient 19 : 19.0
Donor 1 → Patient 20 : 8.0
Donor 1 → Patient 21 : 19.0
Donor 1 → Patient 22 : 19.0
Donor 1 → Patient 23 : 19.0
Donor 1 → Patient 24 : 19.0
Donor 1 → Patient 25 : 19.0
Donor 1 → Patient 26 : 8.0
Donor 1 → Patient 27 : 19.0
Donor 1 → Patient 28 : 19.0
Donor 1 → Patient 29 : 19.0
Donor 1 → Patient 30 : 19.0
Donor 1 → Patient 31 : 19.0
Donor 1 → Patient 32 : 19.0
Donor 1 → Patient 33 : 19.0
Donor 1 → Patient 34 : 19.0
Donor 1 → Patient 35 : 19.0
Donor 1 → Patient 36 : 19.0
Donor 1 → Patient 37 : 19.0
Donor 1 → Patient 38 : 19.0
Donor 1 → Patient 39 : 19.0
Donor 1 → Patient 40 : 19.0
Donor 1 → Patient 41 : 19.0
Donor 1 → Patient 42 : 19.0
Donor 1 → Patient 43 : 8.0
Donor 1 → Patient 44 : 19.0
Donor 1 → Patient 45 : 19.0
Donor 1 → Patient 46 : 19.0
Donor 1 → Patient 47 : 19.0
Donor 1 → Patient 48 : 19.0
Donor 1 → Patient 49 : 19.0
Donor 1 → Patient 50 : 19.0
Donor 1 → Patient 51 : 8.0
Donor 1 → Patient 52 : 19.0
Donor 1 → Patient 53 : 19.0
Donor 1 → Patient 54 : 19.0
Donor 1 → Patient 55 : 19.0
Donor 1 → Patient 56 : 19.0
Donor 1 → Patient 57 : 19.0
Donor 1 → Patient 58 : 8.0
Donor 1 → Patient 59 : 19.0
Donor 1 → Patient 60 : 19.0
Donor 1 → Patient 61 : 8.0
Donor 1 → Patient 62 : 8.0
Donor 1 → Patient 63 : 19.0
Donor 1 → Patient 64 : 19.0
Donor 1 → Patient 65 : 19.0
Donor 1 → Patient 66 : 19.0
Donor 1 → Patient 67 : 8.0
Donor 1 → Patient 68 : 19.0
Donor 1 → Patient 69 : 8.0
Donor 1 → Patient 70 : 8.0
Donor 1 → Patient 71 : 8.0
Donor 1 → Patient 72 : 19.0
Donor 1 → Patient 73 : 19.0
Donor 1 → Patient 74 : 19.0
Donor 1 → Patient 75 : 19.0
Donor 1 → Patient 76 : 8.0
Donor 1 → Patient 77 : 19.0
Donor 1 → Patient 78 : 19.0
Donor 1 → Patient 79 : 19.0
Donor 1 → Patient 80 : 19.0
Donor 1 → Patient 81 : 19.0
Donor 1 → Patient 82 : 19.0
Donor 1 → Patient 83 : 19.0
Donor 1 → Patient 84 : 8.0
Donor 1 → Patient 85 : 19.0
Donor 1 → Patient 86 : 19.0
Donor 1 → Patient 87 : 8.0
Donor 1 → Patient 88 : 8.0
Donor 1 → Patient 89 : 19.0
Donor 1 → Patient 90 : 8.0
Donor 1 → Patient 91 : 19.0
Donor 1 → Patient 92 : 8.0
Donor 1 → Patient 93 : 19.0
Donor 1 → Patient 94 : 19.0
Donor 1 → Patient 95 : 8.0
Donor 1 → Patient 96 : 8.0
Donor 1 → Patient 97 : 19.0
Donor 1 → Patient 98 : 19.0
Donor 1 → Patient 99 : 19.0
Donor 2 → Patient 7 : 7.0
Donor 2 → Patient 11 : 7.0
Donor 2 → Patient 12 : 7.0
Donor 2 → Patient 13 : 7.0
Donor 2 → Patient 19 : 7.0
Donor 2 → Patient 27 : 7.0
Donor 2 → Patient 28 : 7.0
Donor 2 → Patient 29 : 7.0
Donor 2 → Patient 30 : 7.0
Donor 2 → Patient 32 : 7.0
Donor 2 → Patient 33 : 7.0
Donor 2 → Patient 36 : 7.0
Donor 2 → Patient 39 : 7.0
Donor 2 → Patient 46 : 7.0
Donor 2 → Patient 49 : 7.0
Donor 2 → Patient 57 : 7.0
Donor 2 → Patient 60 : 7.0
Donor 2 → Patient 65 : 7.0
Donor 2 → Patient 72 : 7.0
Donor 2 → Patient 74 : 7.0
Donor 2 → Patient 75 : 7.0
Donor 2 → Patient 77 : 7.0
Donor 2 → Patient 80 : 7.0
Donor 2 → Patient 81 : 7.0
Donor 2 → Patient 93 : 7.0
Donor 2 → Patient 97 : 7.0
Donor 3 → Patient 0 : 8.0
Donor 3 → Patient 7 : 16.0
Donor 3 → Patient 11 : 16.0
Donor 3 → Patient 12 : 16.0
Donor 3 → Patient 13 : 16.0
Donor 3 → Patient 19 : 16.0
Donor 3 → Patient 27 : 16.0
Donor 3 → Patient 28 : 16.0
Donor 3 → Patient 29 : 16.0
Donor 3 → Patient 30 : 16.0
Donor 3 → Patient 32 : 16.0
Donor 3 → Patient 33 : 16.0
Donor 3 → Patient 36 : 16.0
Donor 3 → Patient 39 : 16.0
Donor 3 → Patient 43 : 8.0
Donor 3 → Patient 46 : 16.0
Donor 3 → Patient 49 : 16.0
Donor 3 → Patient 51 : 8.0
Donor 3 → Patient 57 : 16.0
Donor 3 → Patient 58 : 8.0
Donor 3 → Patient 60 : 16.0
Donor 3 → Patient 61 : 8.0
Donor 3 → Patient 62 : 8.0
Donor 3 → Patient 65 : 16.0
Donor 3 → Patient 72 : 16.0
Donor 3 → Patient 74 : 16.0
Donor 3 → Patient 75 : 16.0
Donor 3 → Patient 77 : 16.0
Donor 3 → Patient 80 : 16.0
Donor 3 → Patient 81 : 16.0
Donor 3 → Patient 87 : 8.0
Donor 3 → Patient 90 : 8.0
Donor 3 → Patient 92 : 8.0
Donor 3 → Patient 93 : 16.0
Donor 3 → Patient 95 : 8.0
Donor 3 → Patient 96 : 8.0
Donor 3 → Patient 97 : 16.0
Donor 4 → Patient 2 : 9.0
Donor 4 → Patient 3 : 9.0
Donor 4 → Patient 4 : 9.0
Donor 4 → Patient 5 : 9.0
Donor 4 → Patient 6 : 9.0
Donor 4 → Patient 7 : 9.0
Donor 4 → Patient 8 : 9.0
Donor 4 → Patient 9 : 9.0
Donor 4 → Patient 10 : 9.0
Donor 4 → Patient 11 : 9.0
Donor 4 → Patient 12 : 9.0
Donor 4 → Patient 13 : 9.0
Donor 4 → Patient 15 : 9.0
Donor 4 → Patient 16 : 9.0
Donor 4 → Patient 17 : 9.0
Donor 4 → Patient 18 : 9.0
Donor 4 → Patient 19 : 9.0
Donor 4 → Patient 21 : 9.0
Donor 4 → Patient 22 : 9.0
Donor 4 → Patient 23 : 9.0
Donor 4 → Patient 24 : 9.0
Donor 4 → Patient 25 : 9.0
Donor 4 → Patient 27 : 9.0
Donor 4 → Patient 28 : 9.0
Donor 4 → Patient 29 : 9.0
Donor 4 → Patient 30 : 9.0
Donor 4 → Patient 31 : 9.0
Donor 4 → Patient 32 : 9.0
Donor 4 → Patient 33 : 9.0
Donor 4 → Patient 34 : 9.0
Donor 4 → Patient 35 : 9.0
Donor 4 → Patient 36 : 9.0
Donor 4 → Patient 37 : 9.0
Donor 4 → Patient 38 : 9.0
Donor 4 → Patient 39 : 9.0
Donor 4 → Patient 40 : 9.0
Donor 4 → Patient 41 : 9.0
Donor 4 → Patient 42 : 9.0
Donor 4 → Patient 44 : 9.0
Donor 4 → Patient 45 : 9.0
Donor 4 → Patient 46 : 9.0
Donor 4 → Patient 47 : 9.0
Donor 4 → Patient 48 : 9.0
Donor 4 → Patient 49 : 9.0
Donor 4 → Patient 50 : 9.0
Donor 4 → Patient 52 : 9.0
Donor 4 → Patient 53 : 9.0
Donor 4 → Patient 54 : 9.0
Donor 4 → Patient 55 : 9.0
Donor 4 → Patient 56 : 9.0
Donor 4 → Patient 57 : 9.0
Donor 4 → Patient 59 : 9.0
Donor 4 → Patient 60 : 9.0
Donor 4 → Patient 63 : 9.0
Donor 4 → Patient 64 : 9.0
Donor 4 → Patient 65 : 9.0
Donor 4 → Patient 66 : 9.0
Donor 4 → Patient 68 : 9.0
Donor 4 → Patient 72 : 9.0
Donor 4 → Patient 73 : 9.0
Donor 4 → Patient 74 : 9.0
Donor 4 → Patient 75 : 9.0
Donor 4 → Patient 77 : 9.0
Donor 4 → Patient 78 : 9.0
Donor 4 → Patient 79 : 9.0
Donor 4 → Patient 80 : 9.0
Donor 4 → Patient 81 : 9.0
Donor 4 → Patient 82 : 9.0
Donor 4 → Patient 83 : 9.0
Donor 4 → Patient 85 : 9.0
Donor 4 → Patient 86 : 9.0
Donor 4 → Patient 89 : 9.0
Donor 4 → Patient 91 : 9.0
Donor 4 → Patient 93 : 9.0
Donor 4 → Patient 94 : 9.0
Donor 4 → Patient 97 : 9.0
Donor 4 → Patient 98 : 9.0
Donor 4 → Patient 99 : 9.0
Donor 5 → Patient 0 : 8.0
Donor 5 → Patient 1 : 8.0
Donor 5 → Patient 2 : 19.0
Donor 5 → Patient 3 : 19.0
Donor 5 → Patient 5 : 19.0
Donor 5 → Patient 10 : 19.0
Donor 5 → Patient 13 : 19.0
Donor 5 → Patient 16 : 19.0
Donor 5 → Patient 17 : 19.0
Donor 5 → Patient 18 : 19.0
Donor 5 → Patient 31 : 19.0
Donor 5 → Patient 39 : 19.0
Donor 5 → Patient 41 : 19.0
Donor 5 → Patient 44 : 19.0
Donor 5 → Patient 45 : 19.0
Donor 5 → Patient 52 : 19.0
Donor 5 → Patient 53 : 19.0
Donor 5 → Patient 55 : 19.0
Donor 5 → Patient 59 : 19.0
Donor 5 → Patient 62 : 8.0
Donor 5 → Patient 63 : 19.0
Donor 5 → Patient 67 : 8.0
Donor 5 → Patient 73 : 19.0
Donor 5 → Patient 78 : 19.0
Donor 5 → Patient 79 : 19.0
Donor 5 → Patient 81 : 19.0
Donor 5 → Patient 82 : 19.0
Donor 5 → Patient 84 : 8.0
Donor 5 → Patient 87 : 8.0
Donor 5 → Patient 88 : 8.0
Donor 5 → Patient 91 : 19.0
Donor 5 → Patient 98 : 19.0
Donor 5 → Patient 99 : 19.0
Donor 6 → Patient 7 : 13.0
Donor 6 → Patient 11 : 13.0
Donor 6 → Patient 12 : 13.0
Donor 6 → Patient 13 : 13.0
Donor 6 → Patient 19 : 13.0
Donor 6 → Patient 27 : 13.0
Donor 6 → Patient 28 : 13.0
Donor 6 → Patient 29 : 13.0
Donor 6 → Patient 30 : 13.0
Donor 6 → Patient 32 : 13.0
Donor 6 → Patient 33 : 13.0
Donor 6 → Patient 36 : 13.0
Donor 6 → Patient 39 : 13.0
Donor 6 → Patient 46 : 13.0
Donor 6 → Patient 49 : 13.0
Donor 6 → Patient 57 : 13.0
Donor 6 → Patient 60 : 13.0
Donor 6 → Patient 65 : 13.0
Donor 6 → Patient 72 : 13.0
Donor 6 → Patient 74 : 13.0
Donor 6 → Patient 75 : 13.0
Donor 6 → Patient 77 : 13.0
Donor 6 → Patient 80 : 13.0
Donor 6 → Patient 81 : 13.0
Donor 6 → Patient 93 : 13.0
Donor 6 → Patient 97 : 13.0
Donor 7 → Patient 2 : 7.0
Donor 7 → Patient 3 : 7.0
Donor 7 → Patient 4 : 7.0
Donor 7 → Patient 5 : 7.0
Donor 7 → Patient 6 : 7.0
Donor 7 → Patient 7 : 7.0
Donor 7 → Patient 8 : 7.0
Donor 7 → Patient 9 : 7.0
Donor 7 → Patient 10 : 7.0
Donor 7 → Patient 11 : 7.0
Donor 7 → Patient 12 : 7.0
Donor 7 → Patient 13 : 7.0
Donor 7 → Patient 15 : 7.0
Donor 7 → Patient 16 : 7.0
Donor 7 → Patient 17 : 7.0
Donor 7 → Patient 18 : 7.0
Donor 7 → Patient 19 : 7.0
Donor 7 → Patient 21 : 7.0
Donor 7 → Patient 22 : 7.0
Donor 7 → Patient 23 : 7.0
Donor 7 → Patient 24 : 7.0
Donor 7 → Patient 25 : 7.0
Donor 7 → Patient 27 : 7.0
Donor 7 → Patient 28 : 7.0
Donor 7 → Patient 29 : 7.0
Donor 7 → Patient 30 : 7.0
Donor 7 → Patient 31 : 7.0
Donor 7 → Patient 32 : 7.0
Donor 7 → Patient 33 : 7.0
Donor 7 → Patient 34 : 7.0
Donor 7 → Patient 35 : 7.0
Donor 7 → Patient 36 : 7.0
Donor 7 → Patient 37 : 7.0
Donor 7 → Patient 38 : 7.0
Donor 7 → Patient 39 : 7.0
Donor 7 → Patient 40 : 7.0
Donor 7 → Patient 41 : 7.0
Donor 7 → Patient 42 : 7.0
Donor 7 → Patient 44 : 7.0
Donor 7 → Patient 45 : 7.0
Donor 7 → Patient 46 : 7.0
Donor 7 → Patient 47 : 7.0
Donor 7 → Patient 48 : 7.0
Donor 7 → Patient 49 : 7.0
Donor 7 → Patient 50 : 7.0
Donor 7 → Patient 52 : 7.0
Donor 7 → Patient 53 : 7.0
Donor 7 → Patient 54 : 7.0
Donor 7 → Patient 55 : 7.0
Donor 7 → Patient 56 : 7.0
Donor 7 → Patient 57 : 7.0
Donor 7 → Patient 59 : 7.0
Donor 7 → Patient 60 : 7.0
Donor 7 → Patient 63 : 7.0
Donor 7 → Patient 64 : 7.0
Donor 7 → Patient 65 : 7.0
Donor 7 → Patient 66 : 7.0
Donor 7 → Patient 68 : 7.0
Donor 7 → Patient 72 : 7.0
Donor 7 → Patient 73 : 7.0
Donor 7 → Patient 74 : 7.0
Donor 7 → Patient 75 : 7.0
Donor 7 → Patient 77 : 7.0
Donor 7 → Patient 78 : 7.0
Donor 7 → Patient 79 : 7.0
Donor 7 → Patient 80 : 7.0
Donor 7 → Patient 81 : 7.0
Donor 7 → Patient 82 : 7.0
Donor 7 → Patient 83 : 7.0
Donor 7 → Patient 85 : 7.0
Donor 7 → Patient 86 : 7.0
Donor 7 → Patient 89 : 7.0
Donor 7 → Patient 91 : 7.0
Donor 7 → Patient 93 : 7.0
Donor 7 → Patient 94 : 7.0
Donor 7 → Patient 97 : 7.0
Donor 7 → Patient 98 : 7.0
Donor 7 → Patient 99 : 7.0
Donor 8 → Patient 0 : 8.0
Donor 8 → Patient 7 : 19.0
Donor 8 → Patient 11 : 19.0
Donor 8 → Patient 12 : 19.0
Donor 8 → Patient 13 : 19.0
Donor 8 → Patient 19 : 19.0
Donor 8 → Patient 27 : 19.0
Donor 8 → Patient 28 : 19.0
Donor 8 → Patient 29 : 19.0
Donor 8 → Patient 30 : 19.0
Donor 8 → Patient 32 : 19.0
Donor 8 → Patient 33 : 19.0
Donor 8 → Patient 36 : 19.0
Donor 8 → Patient 39 : 19.0
Donor 8 → Patient 43 : 8.0
Donor 8 → Patient 46 : 19.0
Donor 8 → Patient 49 : 19.0
Donor 8 → Patient 51 : 8.0
Donor 8 → Patient 57 : 19.0
Donor 8 → Patient 58 : 8.0
Donor 8 → Patient 60 : 19.0
Donor 8 → Patient 61 : 8.0
Donor 8 → Patient 62 : 8.0
Donor 8 → Patient 65 : 19.0
Donor 8 → Patient 72 : 19.0
Donor 8 → Patient 74 : 19.0
Donor 8 → Patient 75 : 19.0
Donor 8 → Patient 77 : 19.0
Donor 8 → Patient 80 : 19.0
Donor 8 → Patient 81 : 19.0
Donor 8 → Patient 87 : 8.0
Donor 8 → Patient 90 : 8.0
Donor 8 → Patient 92 : 8.0
Donor 8 → Patient 93 : 19.0
Donor 8 → Patient 95 : 8.0
Donor 8 → Patient 96 : 8.0
Donor 8 → Patient 97 : 19.0
Donor 10 → Patient 7 : 7.0
Donor 10 → Patient 11 : 7.0
Donor 10 → Patient 12 : 7.0
Donor 10 → Patient 13 : 7.0
Donor 10 → Patient 19 : 7.0
Donor 10 → Patient 27 : 7.0
Donor 10 → Patient 28 : 7.0
Donor 10 → Patient 29 : 7.0
Donor 10 → Patient 30 : 7.0
Donor 10 → Patient 32 : 7.0
Donor 10 → Patient 33 : 7.0
Donor 10 → Patient 36 : 7.0
Donor 10 → Patient 39 : 7.0
Donor 10 → Patient 46 : 7.0
Donor 10 → Patient 49 : 7.0
Donor 10 → Patient 57 : 7.0
Donor 10 → Patient 60 : 7.0
Donor 10 → Patient 65 : 7.0
Donor 10 → Patient 72 : 7.0
Donor 10 → Patient 74 : 7.0
Donor 10 → Patient 75 : 7.0
Donor 10 → Patient 77 : 7.0
Donor 10 → Patient 80 : 7.0
Donor 10 → Patient 81 : 7.0
Donor 10 → Patient 93 : 7.0
Donor 10 → Patient 97 : 7.0
Donor 11 → Patient 7 : 9.0
Donor 11 → Patient 11 : 9.0
Donor 11 → Patient 12 : 9.0
Donor 11 → Patient 13 : 9.0
Donor 11 → Patient 19 : 9.0
Donor 11 → Patient 27 : 9.0
Donor 11 → Patient 28 : 9.0
Donor 11 → Patient 29 : 9.0
Donor 11 → Patient 30 : 9.0
Donor 11 → Patient 32 : 9.0
Donor 11 → Patient 33 : 9.0
Donor 11 → Patient 36 : 9.0
Donor 11 → Patient 39 : 9.0
Donor 11 → Patient 46 : 9.0
Donor 11 → Patient 49 : 9.0
Donor 11 → Patient 57 : 9.0
Donor 11 → Patient 60 : 9.0
Donor 11 → Patient 65 : 9.0
Donor 11 → Patient 72 : 9.0
Donor 11 → Patient 74 : 9.0
Donor 11 → Patient 75 : 9.0
Donor 11 → Patient 77 : 9.0
Donor 11 → Patient 80 : 9.0
Donor 11 → Patient 81 : 9.0
Donor 11 → Patient 93 : 9.0
Donor 11 → Patient 97 : 9.0
Donor 12 → Patient 0 : 8.0
Donor 12 → Patient 1 : 8.0
Donor 12 → Patient 2 : 13.0
Donor 12 → Patient 3 : 13.0
Donor 12 → Patient 5 : 13.0
Donor 12 → Patient 10 : 13.0
Donor 12 → Patient 13 : 13.0
Donor 12 → Patient 16 : 13.0
Donor 12 → Patient 17 : 13.0
Donor 12 → Patient 18 : 13.0
Donor 12 → Patient 31 : 13.0
Donor 12 → Patient 39 : 13.0
Donor 12 → Patient 41 : 13.0
Donor 12 → Patient 44 : 13.0
Donor 12 → Patient 45 : 13.0
Donor 12 → Patient 52 : 13.0
Donor 12 → Patient 53 : 13.0
Donor 12 → Patient 55 : 13.0
Donor 12 → Patient 59 : 13.0
Donor 12 → Patient 62 : 8.0
Donor 12 → Patient 63 : 13.0
Donor 12 → Patient 67 : 8.0
Donor 12 → Patient 73 : 13.0
Donor 12 → Patient 78 : 13.0
Donor 12 → Patient 79 : 13.0
Donor 12 → Patient 81 : 13.0
Donor 12 → Patient 82 : 13.0
Donor 12 → Patient 84 : 8.0
Donor 12 → Patient 87 : 8.0
Donor 12 → Patient 88 : 8.0
Donor 12 → Patient 91 : 13.0
Donor 12 → Patient 98 : 13.0
Donor 12 → Patient 99 : 13.0
Donor 13 → Patient 0 : 8.0
Donor 13 → Patient 1 : 8.0
Donor 13 → Patient 2 : 16.0
Donor 13 → Patient 3 : 16.0
Donor 13 → Patient 4 : 16.0
Donor 13 → Patient 5 : 16.0
Donor 13 → Patient 6 : 16.0
Donor 13 → Patient 7 : 16.0
Donor 13 → Patient 8 : 16.0
Donor 13 → Patient 9 : 16.0
Donor 13 → Patient 10 : 16.0
Donor 13 → Patient 11 : 16.0
Donor 13 → Patient 12 : 16.0
Donor 13 → Patient 13 : 16.0
Donor 13 → Patient 14 : 8.0
Donor 13 → Patient 15 : 16.0
Donor 13 → Patient 16 : 16.0
Donor 13 → Patient 17 : 16.0
Donor 13 → Patient 18 : 16.0
Donor 13 → Patient 19 : 16.0
Donor 13 → Patient 20 : 8.0
Donor 13 → Patient 21 : 16.0
Donor 13 → Patient 22 : 16.0
Donor 13 → Patient 23 : 16.0
Donor 13 → Patient 24 : 16.0
Donor 13 → Patient 25 : 16.0
Donor 13 → Patient 26 : 8.0
Donor 13 → Patient 27 : 16.0
Donor 13 → Patient 28 : 16.0
Donor 13 → Patient 29 : 16.0
Donor 13 → Patient 30 : 16.0
Donor 13 → Patient 31 : 16.0
Donor 13 → Patient 32 : 16.0
Donor 13 → Patient 33 : 16.0
Donor 13 → Patient 34 : 16.0
Donor 13 → Patient 35 : 16.0
Donor 13 → Patient 36 : 16.0
Donor 13 → Patient 37 : 16.0
Donor 13 → Patient 38 : 16.0
Donor 13 → Patient 39 : 16.0
Donor 13 → Patient 40 : 16.0
Donor 13 → Patient 41 : 16.0
Donor 13 → Patient 42 : 16.0
Donor 13 → Patient 43 : 8.0
Donor 13 → Patient 44 : 16.0
Donor 13 → Patient 45 : 16.0
Donor 13 → Patient 46 : 16.0
Donor 13 → Patient 47 : 16.0
Donor 13 → Patient 48 : 16.0
Donor 13 → Patient 49 : 16.0
Donor 13 → Patient 50 : 16.0
Donor 13 → Patient 51 : 8.0
Donor 13 → Patient 52 : 16.0
Donor 13 → Patient 53 : 16.0
Donor 13 → Patient 54 : 16.0
Donor 13 → Patient 55 : 16.0
Donor 13 → Patient 56 : 16.0
Donor 13 → Patient 57 : 16.0
Donor 13 → Patient 58 : 8.0
Donor 13 → Patient 59 : 16.0
Donor 13 → Patient 60 : 16.0
Donor 13 → Patient 61 : 8.0
Donor 13 → Patient 62 : 8.0
Donor 13 → Patient 63 : 16.0
Donor 13 → Patient 64 : 16.0
Donor 13 → Patient 65 : 16.0
Donor 13 → Patient 66 : 16.0
Donor 13 → Patient 67 : 8.0
Donor 13 → Patient 68 : 16.0
Donor 13 → Patient 69 : 8.0
Donor 13 → Patient 70 : 8.0
Donor 13 → Patient 71 : 8.0
Donor 13 → Patient 72 : 16.0
Donor 13 → Patient 73 : 16.0
Donor 13 → Patient 74 : 16.0
Donor 13 → Patient 75 : 16.0
Donor 13 → Patient 76 : 8.0
Donor 13 → Patient 77 : 16.0
Donor 13 → Patient 78 : 16.0
Donor 13 → Patient 79 : 16.0
Donor 13 → Patient 80 : 16.0
Donor 13 → Patient 81 : 16.0
Donor 13 → Patient 82 : 16.0
Donor 13 → Patient 83 : 16.0
Donor 13 → Patient 84 : 8.0
Donor 13 → Patient 85 : 16.0
Donor 13 → Patient 86 : 16.0
Donor 13 → Patient 87 : 8.0
Donor 13 → Patient 88 : 8.0
Donor 13 → Patient 89 : 16.0
Donor 13 → Patient 90 : 8.0
Donor 13 → Patient 91 : 16.0
Donor 13 → Patient 92 : 8.0
Donor 13 → Patient 93 : 16.0
Donor 13 → Patient 94 : 16.0
Donor 13 → Patient 95 : 8.0
Donor 13 → Patient 96 : 8.0
Donor 13 → Patient 97 : 16.0
Donor 13 → Patient 98 : 16.0
Donor 13 → Patient 99 : 16.0
Donor 14 → Patient 0 : 5.0
Donor 14 → Patient 1 : 5.0
Donor 14 → Patient 2 : 13.0
Donor 14 → Patient 3 : 13.0
Donor 14 → Patient 4 : 13.0
Donor 14 → Patient 5 : 13.0
Donor 14 → Patient 6 : 13.0
Donor 14 → Patient 7 : 13.0
Donor 14 → Patient 8 : 13.0
Donor 14 → Patient 9 : 13.0
Donor 14 → Patient 10 : 13.0
Donor 14 → Patient 11 : 13.0
Donor 14 → Patient 12 : 13.0
Donor 14 → Patient 13 : 13.0
Donor 14 → Patient 14 : 5.0
Donor 14 → Patient 15 : 13.0
Donor 14 → Patient 16 : 13.0
Donor 14 → Patient 17 : 13.0
Donor 14 → Patient 18 : 13.0
Donor 14 → Patient 19 : 13.0
Donor 14 → Patient 20 : 5.0
Donor 14 → Patient 21 : 13.0
Donor 14 → Patient 22 : 13.0
Donor 14 → Patient 23 : 13.0
Donor 14 → Patient 24 : 13.0
Donor 14 → Patient 25 : 13.0
Donor 14 → Patient 26 : 5.0
Donor 14 → Patient 27 : 13.0
Donor 14 → Patient 28 : 13.0
Donor 14 → Patient 29 : 13.0
Donor 14 → Patient 30 : 13.0
Donor 14 → Patient 31 : 13.0
Donor 14 → Patient 32 : 13.0
Donor 14 → Patient 33 : 13.0
Donor 14 → Patient 34 : 13.0
Donor 14 → Patient 35 : 13.0
Donor 14 → Patient 36 : 13.0
Donor 14 → Patient 37 : 13.0
Donor 14 → Patient 38 : 13.0
Donor 14 → Patient 39 : 13.0
Donor 14 → Patient 40 : 13.0
Donor 14 → Patient 41 : 13.0
Donor 14 → Patient 42 : 13.0
Donor 14 → Patient 43 : 5.0
Donor 14 → Patient 44 : 13.0
Donor 14 → Patient 45 : 13.0
Donor 14 → Patient 46 : 13.0
Donor 14 → Patient 47 : 13.0
Donor 14 → Patient 48 : 13.0
Donor 14 → Patient 49 : 13.0
Donor 14 → Patient 50 : 13.0
Donor 14 → Patient 51 : 5.0
Donor 14 → Patient 52 : 13.0
Donor 14 → Patient 53 : 13.0
Donor 14 → Patient 54 : 13.0
Donor 14 → Patient 55 : 13.0
Donor 14 → Patient 56 : 13.0
Donor 14 → Patient 57 : 13.0
Donor 14 → Patient 58 : 5.0
Donor 14 → Patient 59 : 13.0
Donor 14 → Patient 60 : 13.0
Donor 14 → Patient 61 : 5.0
Donor 14 → Patient 62 : 5.0
Donor 14 → Patient 63 : 13.0
Donor 14 → Patient 64 : 13.0
Donor 14 → Patient 65 : 13.0
Donor 14 → Patient 66 : 13.0
Donor 14 → Patient 67 : 5.0
Donor 14 → Patient 68 : 13.0
Donor 14 → Patient 69 : 5.0
Donor 14 → Patient 70 : 5.0
Donor 14 → Patient 71 : 5.0
Donor 14 → Patient 72 : 13.0
Donor 14 → Patient 73 : 13.0
Donor 14 → Patient 74 : 13.0
Donor 14 → Patient 75 : 13.0
Donor 14 → Patient 76 : 5.0
Donor 14 → Patient 77 : 13.0
Donor 14 → Patient 78 : 13.0
Donor 14 → Patient 79 : 13.0
Donor 14 → Patient 80 : 13.0
Donor 14 → Patient 81 : 13.0
Donor 14 → Patient 82 : 13.0
Donor 14 → Patient 83 : 13.0
Donor 14 → Patient 84 : 5.0
Donor 14 → Patient 85 : 13.0
Donor 14 → Patient 86 : 13.0
Donor 14 → Patient 87 : 5.0
Donor 14 → Patient 88 : 5.0
Donor 14 → Patient 89 : 13.0
Donor 14 → Patient 90 : 5.0

In [51]:
cycles = get_all_cycles(adj,3)
print(cycles)

{(2, 27, 16), (46, 98, 64), (11, 46, 73), (13, 72, 62), (23, 94, 68), (29, 52, 93), (13, 37, 41), (72, 82, 90), (2, 29, 62), (38, 62, 64), (7, 75, 82), (11, 81, 67), (12, 98, 88), (13, 14, 57), (29, 68, 37), (36, 41, 48), (65, 86, 95), (14, 54, 73), (6, 77, 67), (7, 27, 11), (3, 81, 77), (12, 73, 31), (6, 13, 82), (10, 19, 67), (37, 98, 54), (11, 74, 27), (16, 56, 32), (16, 87, 99), (27, 67, 84), (19, 29, 38), (4, 97, 82), (28, 81, 43), (2, 57, 16), (3, 33, 36), (3, 74, 37), (72, 77, 96), (12, 52, 93), (43, 57, 79), (79, 90, 81), (4, 74, 98), (10, 72, 78), (19, 64, 32), (24, 46, 37), (38, 92, 64), (13, 44, 57), (2, 36, 78), (3, 12, 98), (11, 28, 32), (33, 81, 38), (69, 99, 96), (19, 43, 94), (19, 84, 95), (36, 73, 94), (1, 48, 27), (16, 86, 32), (27, 97, 84), (24, 41, 43), (16, 28, 27), (12, 82, 93), (7, 13, 89), (7, 46, 37), (19, 61, 84), (19, 94, 32), (16, 65, 94), (43, 82, 68), (1, 25, 16), (19, 71, 48), (0, 27, 58), (16, 81, 38), (88, 91, 97), (7, 25, 99), (19, 73, 94), (7, 64, 27), (1, 4, 78), (4, 68, 37), (6, 60, 32), (43, 82, 85), (46, 89, 85), (7, 41, 43), (19, 89, 38), (16, 19, 99), (34, 99, 68), (27, 44, 49), (75, 79, 92), (1, 80, 73), (23, 31, 38), (51, 72, 90), (74, 81, 77), (1, 57, 89), (32, 61, 48), (58, 62, 91), (32, 38, 64), (32, 79, 65), (35, 99, 96), (13, 27, 22), (16, 88, 54), (16, 24, 69), (39, 52, 49), (11, 77, 28), (13, 29, 68), (41, 50, 81), (58, 80, 81), (32, 56, 54), (6, 32, 27), (19, 96, 54), (24, 64), (82, 88, 83), (7, 73, 89), (57, 81, 77), (1, 87, 89), (41, 85, 75), (1, 80), (58, 92, 91), (32, 68, 64), (62, 98, 76), (63, 79, 87), (13, 24, 74), (13, 57, 22), (13, 98, 23), (10, 27, 38), (39, 82, 49), (1, 10, 27), (70, 93, 72), (29, 32, 86), (41, 80, 81), (7, 78, 59), (13, 36, 84), (13, 77, 85), (54, 64), (31, 80), (13, 52, 28), (74, 77, 92), (4, 24, 64), (4, 98, 13), (19, 74, 49), (73, 78, 88), (27, 29, 60), (13, 54, 74), (13, 87, 22), (36, 81, 65), (10, 57, 38), (72, 80, 73), (3, 36, 13), (88, 94, 98), (3, 96, 64), (12, 88, 18), (56, 89, 62), (57, 65, 82), (29, 62, 86), (73, 96, 78), (62, 64, 90), (13, 82, 28), (57, 77, 92), (4, 54, 64), (8, 32, 74), (17, 65, 29), (27, 59, 60), (19, 81, 65), (54, 64, 98), (71, 94, 98), (25, 44, 81), (38, 68, 96), (13, 61, 90), (36, 88, 81), (19, 23, 60), (20, 73, 29), (62, 77, 87), (54, 99, 92), (12, 62, 86), (29, 92, 86), (43, 67, 72), (0, 72, 69), (17, 19, 34), (49, 65, 82), (51, 57, 77), (68, 96), (8, 62, 74), (39, 79, 77), (0, 65, 29), (4, 30, 13), (13, 89, 44), (17, 95, 29), (43, 44, 61), (27, 89, 60), (2, 81, 65), (12, 16, 91), (54, 94, 98), (16, 96, 25), (31, 72, 61), (32, 48, 81), (19, 88, 81), (34, 79, 61), (51, 75, 67), (37, 99, 92), (77, 99, 94), (16, 98, 71), (7, 81, 60), (39, 62, 66), (10, 13, 65), (41, 93, 46), (16, 50, 30), (34, 81), (56, 74, 73), (27, 61, 82), (32, 43, 87), (49, 72, 98), (69, 98, 88), (59, 81, 73), (33, 57, 46), (7, 33, 19), (37, 94, 98), (43, 51, 77), (4, 37, 29), (17, 28, 96), (73, 81, 89), (14, 72, 61), (32, 78, 81), (27, 41), (16, 29, 92), (65, 81, 99), (12, 91, 19), (0, 33, 90), (0, 74, 91), (13, 67, 39), (6, 72, 71), (27, 73, 92), (31, 79, 77), (67, 71, 78), (7, 12, 81), (24, 42, 81), (26, 39, 67), (74, 75, 99), (32, 71, 41), (24, 93, 46), (40, 73, 77), (41, 49, 97), (25, 99, 87), (32, 73, 87), (24, 35, 41), (67, 89, 68), (41, 97), (33, 87, 46), (13, 21, 44), (26, 51, 77), (0, 28, 96), (4, 34, 81), (31, 74, 83), (56, 81, 89), (12, 63, 41), (16, 40), (48, 81, 99), (39, 87, 72), (14, 79, 77), (3, 46, 30), (64, 71, 94), (7, 42, 81), (13, 74, 55), (57, 75, 99), (19, 77, 26), (6, 77, 14), (23, 73, 77), (3, 81, 24), (38, 64, 57), (13, 16, 50), (39, 99, 82), (28, 32, 98), (38, 41, 73), (12, 17, 46), (29, 47, 46), (11, 46), (16, 87, 46), (39, 41, 77), (27, 67, 31), (18, 39, 67), (31, 63, 82), (38, 76, 67), (31, 40, 98), (5, 16, 71), (6, 33, 92), (22, 87, 72), (31, 81, 99), (23, 56), (26, 29, 72), (18, 32, 27), (14, 51, 72), (19, 33, 77), (89, 91, 96), (22, 39, 31), (38, 94, 57), (22, 99, 82), (27, 62, 37), (27, 81, 87), (1, 98, 61), (30, 82, 68), (11, 32, 98), (28, 62, 98), (56, 65, 94), (38, 71, 73), (13, 23, 66), (35, 41, 89), (36, 91, 58), (27, 97, 31), (14, 63, 82), (27, 74, 47), (13, 99, 61), (18, 46, 83), (79, 87, 80), (5, 87, 72), (19, 61, 31), (16, 65, 41), (29, 89, 56), (19, 38, 47), (23, 75, 99), (2, 33, 77), (33, 72, 57), (7, 89, 31), (0, 27, 5), (1, 29, 82), (4, 64, 57), (5, 99, 82), (10, 81, 87), (27, 92, 37), (54, 56, 74), (28, 92, 98), (6, 27, 31), (10, 97, 31), (34, 41, 37), (7, 27, 92), (13, 30, 82), (16, 19, 46), (17, 36, 67), (27, 30, 98), (62, 87, 80), (16, 37, 63), (76, 87, 96), (8, 19, 56), (1, 24, 88), (1, 57, 36), (46, 68, 94), (19, 68, 47), (23, 74, 32), (16, 72, 57), (0, 57, 5), (62, 99, 90), (24, 27, 68), (35, 99, 43), (41, 57, 68), (41, 98, 69), (8, 12, 16), (7, 22, 98), (8, 72, 67), (19, 70, 93), (37, 56, 74), (1, 36, 98), (31, 64, 37), (32, 81, 58), (6, 57, 31), (60, 61, 70), (2, 75, 87), (13, 29, 15), (7, 98, 93), (0, 36, 67), (16, 49, 46), (43, 89, 48), (22, 88, 27), (10, 30, 98), (16, 67, 63), (17, 43, 83), (1, 13, 87), (1, 87, 36), (41, 52, 74), (14, 52, 27), (33, 74, 79), (22, 67, 89), (14, 29, 43), (26, 77, 38), (1, 89, 82), (24, 57, 68), (29, 39, 73), (41, 87, 68), (13, 24, 21), (13, 84, 72), (32, 88, 74), (5, 88, 27), (29, 32, 33), (77, 98, 86), (13, 77, 32), (16, 97, 63), (14, 43, 99), (24, 52, 74), (29, 34, 79), (14, 82, 27), (41, 82, 74), (7, 80, 52), (8, 97, 73), (13, 38, 77), (5, 67, 89), (70, 72, 81), (19, 41, 48), (31, 89, 43), (7, 57, 68), (12, 39, 73), (13, 15, 93), (21, 31, 27), (23, 37, 99), (24, 87, 68), (13, 54, 21), (56, 73, 65), (62, 72, 91), (1, 96, 98), (29, 46, 89), (13, 31, 37), (73, 80, 81), (18, 77, 38), (29, 62, 33), (65, 80, 91), (14, 73, 99), (24, 82, 74), (29, 64, 79), (17, 80, 99), (82, 92, 98), (56, 68, 71), (32, 70, 33), (29, 41, 95), (14, 89, 43), (13, 26, 43), (73, 75, 87), (4, 31, 27), (63, 73), (65, 98, 81), (1, 2, 32), (32, 72, 79), (3, 33, 12), (81, 90), (13, 61, 37), (56, 80, 81), (31, 73, 75), (28, 77, 85), (12, 62, 33), (29, 92, 33), (0, 72, 16), (70, 97, 87), (28, 93, 29), (46, 99, 49), (72, 89, 82), (7, 82, 74), (13, 40, 99), (29, 94, 79), (12, 41, 95), (56, 75, 87), (12, 99, 73), (78, 87, 92), (27, 56, 59), (28, 72, 91), (12, 16, 38), (16, 82, 74), (68, 71, 77), (69, 88, 98), (17, 74, 38), (36, 62, 96), (1, 85, 43), (19, 71, 24), (29, 99, 49), (34, 81, 54), (8, 57, 27), (10, 13, 12), (72, 96, 98), (20, 82, 38), (43, 76, 81), (16, 77, 80), (27, 61, 29), (6, 19, 7), (18, 33, 65), (17, 28, 43), (10, 33, 75), (23, 91, 65), (16, 29, 39), (13, 90), (8, 11, 32), (27, 40, 91), (0, 74, 38), (1, 16, 64), (1, 90, 13), (40, 98, 81), (17, 81, 54), (8, 87, 27), (32, 98, 91), (6, 74, 64), (13, 46, 48), (41, 67, 61), (27, 91, 29), (44, 87, 92), (6, 49, 7), (7, 32, 91), (29, 77, 44), (8, 96), (7, 30, 18), (16, 84, 96), (0, 28, 43), (58, 74, 77), (11, 13, 19), (68, 73, 99), (16, 59, 39), (52, 77, 97), (56, 83, 82), (1, 46, 64), (67, 68, 77), (23, 98, 81), (38, 89, 61), (13, 41, 54), (1, 23, 80), (22, 59, 65), (7, 19, 44), (23, 73, 24), (29, 72, 50), (1, 99, 75), (12, 44, 96), (38, 96), (5, 41, 75), (56, 78, 88), (30, 31, 77), (31, 81, 46), (47, 61, 77), (19, 58, 81), (32, 82, 96), (37, 44, 62), (1, 22, 13), (13, 71, 54), (5, 59, 65), (14, 51, 19), (7, 16, 96), (38, 96, 77), (80, 99, 89), (57, 82, 62), (62, 64, 67), (23, 47, 92), (13, 64, 14), (39, 73, 97), (14, 30, 81), (91, 96, 94), (65, 72, 67), (27, 41, 46), (1, 17, 19), (31, 37, 97), (5, 87, 19), (63, 98, 89), (13, 43, 76), (16, 32, 40), (4, 89, 61), (10, 46, 40), (57, 77, 68), (1, 52, 13), (10, 11, 19), (11, 27, 51), (13, 18, 19), (30, 73, 87), (40, 82, 62), (46, 81, 88), (37, 86, 72), (44, 65, 63), (1, 31, 75), (62, 71, 83), (5, 82, 25), (36, 88, 57), (48, 72, 67), (27, 71, 46), (1, 47, 19), (38, 80, 82), (27, 48, 62), (13, 73, 76), (62, 89, 73), (2, 65, 97), (28, 87, 51), (25, 91, 61), (26, 33, 87), (1, 26, 81), (1, 59, 29), (79, 96, 89), (33, 46, 72), (20, 87, 61), (1, 3, 97), (5, 73, 97), (49, 77, 68), (19, 88, 57), (24, 29, 61), (67, 83, 88), (63, 82, 94), (80, 82), (34, 98, 87), (43, 56, 47), (62, 78, 99), (1, 77, 19), (17, 43, 30), (26, 61, 41), (27, 78, 62), (75, 78, 84), (46, 65, 93), (7, 17, 51), (38, 87, 98), (1, 56, 81), (1, 89, 29), (49, 72, 74), (62, 96, 89), (16, 46, 72), (29, 70, 87), (3, 87, 61), (7, 93, 46), (8, 28, 65), (17, 61, 20), (1, 33, 97), (7, 29, 61), (8, 46, 82), (27, 32, 67), (23, 60, 57), (36, 84, 72), (73, 93, 75), (57, 97, 73), (18, 80, 98), (16, 41, 78), (58, 77), (7, 47, 51), (30, 41, 94), (16, 99, 56), (5, 67, 36), (7, 24, 67), (23, 37, 46), (0, 72), (34, 82, 92), (40, 44, 62), (41, 61, 83), (2, 13, 41), (37, 89, 73), (39, 81, 68), (13, 58, 87), (32, 44, 72), (24, 47, 27), (12, 82), (3, 65, 56), (60, 65, 85), (13, 33, 30), (74, 99, 95), (32, 62, 89), (5, 81, 92), (15, 30, 16), (14, 40, 98), (4, 56, 31), (16, 71, 78), (65, 82, 84), (39, 99, 58), (1, 27, 36), (65, 93), (32, 74, 99), (46, 48, 58), (23, 44, 62), (12, 13, 88), (29, 43, 88), (3, 19, 61), (16, 83, 88), (81, 90, 96), (13, 28, 36), (22, 81, 68), (13, 88, 87), (73, 77, 80), (41, 68, 99), (11, 72, 62), (23, 32), (29, 59, 32), (21, 81, 37), (39, 88, 84), (65, 77, 90), (57, 99, 95), (19, 27, 73), (30, 99, 48), (32, 92, 89), (23, 97, 73), (41, 84, 43), (13, 81, 47), (4, 12, 82), (17, 46, 31), (24, 89, 37), (28, 72, 38), (64, 90, 96), (13, 93, 57), (29, 73, 88), (25, 41, 27), (19, 22, 79), (32, 46, 94), (24, 68, 99), (12, 59, 32), (13, 35, 52), (29, 89, 32), (4, 81, 37), (73, 84, 96), (2, 27, 73), (19, 57, 73), (11, 19, 27), (13, 37, 98), (27, 86, 33), (10, 81, 63), (46, 73, 64), (80, 98, 81), (13, 47, 62), (16, 77, 27), (4, 19, 98), (27, 88, 79), (19, 50, 33), (24, 32, 38), (72, 98, 91), (3, 95, 32), (8, 77, 37), (16, 19, 22), (12, 73, 88), (1, 41, 68), (19, 85, 27), (24, 67, 32), (36, 82, 79), (13, 37), (16, 56, 89), (1, 57, 12), (1, 76, 62), (19, 29, 95), (2, 57, 73), (3, 74, 94), (11, 49, 27), (16, 31, 32), (19, 87, 73), (29, 96, 48), (37, 73, 54), (32, 98, 38), (19, 64, 89), (24, 46, 94), (28, 97, 44), (39, 67, 95), (27, 58, 28), (7, 32, 38), (24, 62, 38), (8, 43), (16, 84, 43), (43, 50, 96), (1, 71, 68), (36, 87, 49), (67, 93, 81), (19, 82, 79), (1, 87, 12), (1, 23, 27), (4, 13, 37), (16, 61, 32), (26, 96, 64), (27, 72, 84), (75, 88, 77), (7, 46, 94), (19, 94, 89), (1, 25, 73), (1, 99, 22), (6, 81, 27), (30, 79, 65), (10, 77, 78), (67, 88, 87), (12, 44, 43), (13, 20, 63), (38, 43), (24, 92, 38), (27, 65, 44), (32, 47, 49), (50, 93, 81), (41, 99, 54), (3, 27, 32), (7, 64, 84), (4, 8, 43), (13, 96, 58), (4, 68, 94), (35, 44, 96), (19, 58, 28), (32, 82, 43), (19, 89, 95), (24, 30, 99), (27, 77, 54), (31, 83, 39), (5, 59, 12), (23, 72, 96), (7, 16, 43), (0, 80, 99), (28, 29, 44), (29, 46, 65), (10, 65), (1, 32, 89), (4, 22, 99), (32, 77, 49), (13, 27, 79), (24, 99, 54), (29, 81, 59), (4, 38, 43), (32, 54, 65), (7, 11, 49), (7, 30, 99), (13, 43, 23), (11, 77, 85), (5, 31, 34), (19, 65, 44), (6, 65, 32), (20, 41, 64), (32, 89, 59), (13, 78, 17), (11, 29, 44), (12, 79, 13), (38, 70, 92), (54, 60, 87), (28, 77, 61), (3, 29, 54), (46, 83, 81), (7, 99, 54), (12, 81, 59), (13, 57, 79), (13, 98, 80), (62, 73, 76), (32, 84, 65), (52, 75), (38, 47, 81), (13, 73, 23), (61, 74, 72), (87, 98, 99), (35, 91, 46), (29, 65, 91), (37, 48, 77), (73, 99, 83), (39, 98, 50), (19, 72, 60), (2, 7, 39), (8, 39, 13), (7, 94, 60), (62, 68, 82), (16, 18, 65), (29, 83, 81), (47, 81), (59, 72, 92), (13, 87, 79), (1, 79, 39), (4, 73, 13), (13, 64, 95), (44, 74, 72), (32, 91, 81), (3, 11, 13), (7, 77, 49), (13, 80, 39), (61, 81, 88), (35, 98, 62), (24, 84, 65), (29, 37, 86), (33, 43, 71), (13, 82, 85), (70, 75, 88), (75, 98, 94), (8, 46, 29), (16, 48, 65), (43, 88, 67), (0, 33, 13), (62, 75, 98), (23, 27, 56), (16, 25, 81), (7, 31, 54), (33, 96, 82), (83, 88, 99), (64, 82, 89), (16, 41, 25), (17, 77, 96), (13, 46, 24), (27, 52, 77), (32, 34, 82), (41, 86, 87), (7, 24, 14), (0, 19), (16, 43, 71), (43, 83, 73), (59, 97, 98), (86, 96, 99), (27, 87, 71), (24, 72, 31), (16, 20, 87), (50, 80, 87), (0, 65, 86), (23, 57, 56), (16, 55, 81), (16, 96, 82), (35, 82, 67), (16, 71, 25), (0, 77, 96), (40, 41, 88), (14, 17, 61), (27, 82, 77), (31, 47, 61), (32, 64, 82), (24, 86, 87), (75, 82, 99), (32, 92), (38, 60, 46), (0, 19, 91), (16, 73, 71), (32, 41, 98), (16, 50, 87), (33, 80, 87), (7, 56, 60), (39, 78, 67), (13, 88, 34), (58, 65, 98), (81, 92, 89), (13, 65, 50), (16, 85, 81), (23, 64, 72), (28, 46, 77), (41, 70, 92), (3, 72, 19), (13, 67, 96), (14, 47, 61), (44, 77, 73), (32, 94, 82), (7, 86, 87), (29, 38, 41), (29, 98, 92), (38, 90, 46), (13, 42, 39), (14, 24, 77), (31, 54, 77), (32, 71, 98), (3, 51, 81), (38, 67, 62), (81, 87, 95), (4, 32, 92), (16, 80, 87), (22, 78, 67), (27, 60, 72), (32, 46, 41), (80, 88, 91), (49,), (24, 35, 98), (24, 68, 46), (28, 74, 31), (41, 65, 98), (47, 62, 89), (64, 92, 89), (2, 27, 20), (19, 24, 72), (46, 98, 68), (11, 46, 77), (12, 63, 98), (16, 97), (57, 98), (23, 94, 72), (24, 70, 92), (1, 29, 5), (14, 77, 61), (38, 62, 68), (13, 14, 61), (29, 68, 41), (12, 98, 92), (4, 60, 46), (14, 54, 77), (18, 60, 62), (19, 36, 82), (6, 77, 71), (7, 27, 15), (38, 97, 62), (17, 96, 41), (5, 78, 67), (10, 60, 72), (3, 58, 97), (24, 34, 31), (11, 74, 31), (16, 56, 36), (47, 92, 89), (52, 74, 94), (27, 67, 88), (1, 43, 61), (31, 77, 37), (28, 81, 47), (3, 74, 41), (19, 54, 72), (87, 98), (10, 12, 31), (63, 99, 74), (26, 43, 27), (13, 44, 61), (38, 92, 68), (31, 56, 99), (39, 67, 42), (2, 36, 82), (2, 77, 83), (17, 27, 62), (22, 39, 88), (3, 28, 46), (7, 34, 31), (19, 82, 26), (11, 30, 82), (46, 82, 73), (16, 86, 36), (27, 97, 88), (1, 73, 61), (23, 65, 27), (50, 65, 74), (1, 50, 77), (27, 72, 31), (15, 65, 37), (1, 89, 5), (7, 13, 93), (19, 61, 88), (16, 65, 98), (46, 77, 79), (7, 48, 87), (7, 89, 88), (0, 27, 62), (60, 77, 95), (26, 75, 73), (27, 51, 93), (44, 61, 54), (18, 97, 78), (67, 90, 80), (29, 82, 73), (7, 64, 31), (1, 4, 82), (4, 68, 41), (6, 27, 88), (18, 74, 94), (35, 44, 43), (10, 97, 88), (33, 65, 74), (7, 41, 47), (34, 41, 94), (41, 43, 69), (50, 95, 74), (57, 74, 65), (23, 72, 43), (41, 78, 63), (48, 57, 54), (34, 82, 68), (27, 46, 99), (31, 85, 32), (23, 74, 89), (10, 12), (13, 17, 62), (17, 87, 62), (15, 74, 99), (8, 12, 73), (23, 49, 32), (29, 48, 58), (77, 89, 81), (47, 60, 96), (31, 64, 94), (41, 73, 69), (33, 95, 74), (11, 77, 32), (13, 29, 72), (4, 56, 7), (5, 91, 32), (19, 32, 43), (6, 32, 31), (19, 96, 58), (24, 68), (82, 88, 87), (7, 73, 93), (25, 59, 74), (31, 57, 54), (32, 33, 74), (48, 87, 54), (3, 13, 57), (14, 85, 32), (62, 98, 80), (77, 79), (13, 24, 78), (13, 98, 27), (39, 88, 60), (47, 90, 96), (19, 74), (16, 95, 74), (13, 59, 72), (4, 86, 7), (1, 82, 99), (29, 32, 90), (2, 32, 43), (19, 62, 43), (13, 77, 89), (54, 68), (38, 49, 74), (13, 75, 16), (44, 46, 65), (19, 39, 59), (72, 85), (13, 52, 32), (4, 24, 68), (49, 75, 81), (81, 97, 88), (27, 29, 64), (13, 54, 78), (2, 46, 99), (13, 31, 94), (29, 85, 74), (49, 74), (57, 65, 86), (1, 81, 32), (71, 99, 96), (29, 62, 90), (73, 96, 82), (4, 19, 74), (36, 41, 81), (18, 93, 39), (19, 69, 59), (29, 37, 33), (12, 67, 84), (61, 84), (13, 82, 32), (4, 54, 68), (32, 70, 90), (81, 86, 87), (10, 29, 64), (70, 77, 81), (60, 62, 82), (77, 92, 82), (39, 84, 75), (13, 61, 94), (43, 90, 60), (19, 23, 64), (62, 77, 91), (54, 99, 96), (12, 62, 90), (16, 27, 74), (0, 72, 73), (1, 14, 99), (61, 78, 87), (19, 99, 59), (17, 19, 38), (17, 60, 39), (29, 44, 49), (3, 61, 23), (64, 86, 87), (68, 92, 72), (39, 79, 81), (0, 65, 33), (13, 89, 48), (27, 89, 64), (68, 69, 88), (12, 16, 95), (43, 62, 82), (16, 96, 29), (60, 92, 82), (0, 7, 28), (31, 72, 65), (2, 97, 13), (34, 79, 65), (37, 99, 96), (16, 38, 24), (77, 99, 98), (16, 98, 75), (49, 60, 92), (19, 71, 81), (10, 77, 54), (7, 21, 13), (7, 81, 64), (0, 19, 38), (17, 90, 39), (10, 13, 69), (24, 28, 29), (56, 74, 77), (27, 61, 86), (30, 91, 51), (6, 19, 64), (6, 93, 13), (32, 43, 91), (59, 81, 77), (33, 57, 50), (7, 74, 24), (13, 32, 49), (68, 99, 88), (16, 52, 80), (43, 92, 82), (0, 97, 79), (16, 29, 96), (16, 68, 24), (31, 79, 81), (41, 88, 56), (57, 68, 87), (29, 91), (58, 95, 72), (1, 65, 13), (40, 73, 81), (7, 28, 29), (73, 76, 99), (32, 73, 91), (54, 65, 57), (67, 89, 72), (33, 87, 50), (13, 62, 49), (1, 44, 75), (30, 98, 67), (71, 72, 73), (58, 72, 61), (84, 96, 88), (11, 46, 24), (39, 87, 76), (4, 50, 29), (14, 79, 81), (23, 38, 87), (3, 46, 34), (18, 27, 61), (23, 73, 81), (28, 96, 87), (38, 64, 61), (13, 16, 54), (30, 52, 72), (48, 58, 92), (10, 60, 19), (37, 65, 57), (38, 41, 77), (64, 89, 88), (39, 41, 81), (13, 92, 49), (31, 44, 36), (54, 72, 73), (67, 96, 88), (7, 37, 91), (6, 33, 96), (32, 96, 51), (23, 68, 87), (72, 79, 93), (18, 32, 31), (31, 56, 46), (5, 73, 20), (44, 81, 88), (2, 77, 30), (19, 33, 81), (27, 62, 41), (1, 38, 14), (30, 82, 72), (19, 84, 46), (46, 49, 72), (38, 71, 77), (13, 64, 71), (36, 91, 62), (27, 64, 87), (10, 32, 14), (19, 86, 92), (72, 74, 99), (3, 30, 39), (33, 60, 51), (25, 82, 56), (13, 99, 65), (61, 81, 64), (5, 87, 76), (13, 76, 81), (16, 32, 97), (78, 88, 80), (10, 46, 97), (19, 38, 51), (62, 92, 78), (67, 74, 83), (41, 91, 57), (2, 33, 81), (63, 73, 89), (4, 64, 61), (27, 92, 41), (1, 68, 14), (29, 49, 72), (0, 29, 55), (7, 8, 46), (19, 56, 41), (24, 38, 46), (50, 62, 73), (17, 77, 72), (1, 6, 75), (18, 57, 37), (62, 87, 84), (29, 61, 82), (8, 60, 61), (26, 72, 99), (43, 61, 98), (19, 68, 51), (24, 91, 57), (41, 98, 73), (15, 74, 46), (8, 72, 71), (87, 89, 96), (27, 99, 57), (32, 81, 62), (60, 61, 74), (33, 62, 73), (7, 38, 46), (50, 92, 73), (75, 99, 79), (0, 77, 72), (22, 88, 31), (14, 36, 87), (1, 77, 76), (67, 99, 89), (17, 43, 87), (33, 97, 67), (34, 73, 87), (8, 90, 61), (26, 61, 98), (61, 77, 79), (7, 91, 57), (47, 74, 99), (24, 98, 73), (13, 24, 25), (57, 60, 90), (31, 36, 63), (16, 85, 57), (6, 29, 57), (17, 61, 77), (43, 84, 58), (15, 81, 62), (59, 75, 99), (16, 62, 73), (33, 92, 73), (7, 68, 46), (65, 73, 79), (4, 72, 56), (5, 88, 31), (29, 32, 37), (58, 77, 84), (77, 98, 90), (24, 75, 62), (13, 77, 36), (4, 49, 72), (16, 97, 67), (21, 79, 72), (41, 82, 78), (13, 19, 31), (74, 85, 96), (4, 65, 16), (18, 65, 32), (19, 41, 52), (14, 27), (47, 62, 65), (64, 92, 65), (39, 44, 58), (13, 54, 25), (65, 68, 85), (32, 83, 84), (2, 13, 98), (64, 69, 81), (13, 31, 41), (13, 72, 42), (16, 92, 73), (27, 31, 57), (29, 62, 37), (37, 64, 73), (7, 75, 62), (11, 81, 47), (13, 33, 87), (38, 81, 94), (4, 79, 72), (15, 30, 73), (18, 19, 37), (55, 87, 64), (57, 85, 96), (32, 37, 89), (6, 13, 62), (73, 98, 75), (28, 65, 79), (5, 99), (29, 41, 99), (20, 88, 73), (41, 89, 94), (11, 93, 57), (47, 92, 65), (65, 98, 85), (1, 2, 36), (4, 97, 62), (81, 94), (64, 99, 81), (13, 28, 93), (13, 61, 41), (4, 33, 77), (46, 64, 59), (12, 62, 37), (29, 92, 37), (21, 81, 94), (56, 63, 81), (27, 79, 74), (28, 93, 33), (3, 12, 78), (72, 89, 86), (19, 43, 74), (36, 73, 74), (11, 65, 79), (12, 41, 99), (35, 99), (24, 89, 94), (29, 71, 99), (13, 56, 47), (17, 62, 32), (33, 77, 84), (78, 87, 96), (28, 72, 95), (29, 87, 43), (72, 84, 92), (46, 94, 59), (7, 46, 17), (68, 71, 81), (16, 98, 22), (4, 81, 94), (19, 71, 28), (11, 19, 84), (33, 72, 90), (7, 81, 11), (27, 86, 90), (36, 78, 44), (7, 25, 79), (19, 73, 74), (68, 89, 71), (27, 61, 33), (32, 43, 38), (17, 92, 32), (19, 50, 90), (61, 87, 96), (8, 77, 94), (12, 87, 43), (16, 52, 27), (4, 35, 99), (85, 96, 87), (27, 63, 79), (24, 67, 89), (16, 29, 43), (13, 94), (51, 72, 70), (1, 16, 68), (31, 46, 80), (49, 57, 91), (29, 38), (16, 31, 89), (43, 71, 91), (1, 32, 12), (18, 28, 75), (32, 38, 44), (6, 74, 68), (32, 98, 95), (25, 99, 38), (27, 91, 33), (32, 73, 38), (41, 67, 65), (7, 32, 95), (44, 87, 96), (13, 29, 48), (57, 98, 61), (31, 74, 34), (58, 74, 81), (68, 96, 87), (50, 61, 65), (11, 13, 23), (24, 37, 38), (27, 70, 95), (1, 46, 68), (67, 68, 81), (38, 89, 65), (13, 41, 58), (4, 13, 94), (16, 61, 89), (14, 62, 24), (32, 68, 44), (55, 62, 87), (29, 72, 54), (8, 61, 99), (4, 29, 38), (22, 52, 29), (27, 98, 49), (3, 27, 89), (7, 37, 38), (33, 61, 65), (63, 91, 77), (30, 3

In [44]:
weights = [compute_cycle_weight(c, surv) for c in cycles]
z, sol = kep_cycle(adj, cycles, weights)
print("Max total survival time:", z)
for s in sol:
    print("Cycle:", s)

Gurobi 12.0.1:Gurobi 12.0.1: optimal solution; objective 1146
24524 simplex iterations
1 branching node
Max total survival time: 1146.0
Cycle: (41, 70, 92)
Cycle: (27, 35, 52)
Cycle: (33,)
Cycle: (29, 85, 58)
Cycle: (37,)
Cycle: (94,)
Cycle: (21, 31, 56)
Cycle: (46, 47)
Cycle: (10, 49, 80)
Cycle: (48, 60, 72)
Cycle: (54,)
Cycle: (20, 98, 99)
Cycle: (34, 44, 57)
Cycle: (11, 30, 18)
Cycle: (19, 26, 95)
Cycle: (4, 38, 24)
Cycle: (36, 84, 90)
Cycle: (62, 76, 79)
Cycle: (1, 8, 97)
Cycle: (63,)
Cycle: (67, 83, 78)
Cycle: (32, 68, 50)
Cycle: (2, 77, 69)
Cycle: (17, 28, 74)
Cycle: (7, 15, 93)
Cycle: (64,)
Cycle: (23, 73, 43)
Cycle: (42, 81)
Cycle: (5, 91, 39)
Cycle: (6, 12, 88)
Cycle: (25, 59, 65)
Cycle: (3, 61, 22)
Cycle: (55, 87, 96)
Cycle: (89,)
Cycle: (75, 82, 86)
Cycle: (14, 40, 16)
Cycle: (13, 71, 66)

In [ ]:
cycles = get_all_cycles(adj,3)
weights = [compute_cycle_weight(c, surv) for c in cycles]
z, sol = kep_cycle(adj,cycles, weights)
print("solution:", z, sol)

Gurobi 12.0.1:Gurobi 12.0.1: optimal solution; objective 1146
24524 simplex iterations
1 branching node
solution: 1146.0 [(41, 70, 92), (27, 35, 52), (33,), (29, 85, 58), (37,), (94,), (21, 31, 56), (46, 47), (10, 49, 80), (48, 60, 72), (54,), (20, 98, 99), (34, 44, 57), (11, 30, 18), (19, 26, 95), (4, 38, 24), (36, 84, 90), (62, 76, 79), (1, 8, 97), (63,), (67, 83, 78), (32, 68, 50), (2, 77, 69), (17, 28, 74), (7, 15, 93), (64,), (23, 73, 43), (42, 81), (5, 91, 39), (6, 12, 88), (25, 59, 65), (3, 61, 22), (55, 87, 96), (89,), (75, 82, 86), (14, 40, 16), (13, 71, 66)]

In [53]:
print(adj)

{0: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 2: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 3: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 4: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 5: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 6: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 7: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 8: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 9: [], 10: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 11: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 12: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 13: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 14: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 15: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 16: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 17: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 18: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 19: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 20: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 21: [2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 63, 73, 78, 79, 81, 82, 91, 98, 99], 22: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 23: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 24: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 25: [2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 63, 73, 78, 79, 81, 82, 91, 98, 99], 26: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 27: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 28: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 29: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 30: [2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 63, 73, 78, 79, 81, 82, 91, 98, 99], 31: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 32: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 33: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 34: [2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 63, 73, 78, 79, 81, 82, 91, 98, 99], 35: [2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 63, 73, 78, 79, 81, 82, 91, 98, 99], 36: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 37: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 38: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 39: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 40: [2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 63, 73, 78, 79, 81, 82, 91, 98, 99], 41: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 42: [13, 39, 81], 43: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 44: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 45: [], 46: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 47: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 48: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 49: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 50: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 51: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 52: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 53: [], 54: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 55: [0, 13, 39, 62, 81, 87], 56: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 57: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 58: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 59: [7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 46, 49, 57, 60, 65, 72, 74, 75, 77, 80, 81, 93, 97], 60: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 61: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 62: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 63: [2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 63, 73, 78, 79, 81, 82, 91, 98, 99], 64: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 65: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 66: [13, 39, 81], 67: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 68: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 69: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 70: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 71: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 72: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 73: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 74: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 59, 60, 63, 64, 65, 66, 68, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 85, 86, 89, 91, 93, 94, 97, 98, 99], 75: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 76: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 77: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 78: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 79: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 80: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 81: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 82: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 83: [0, 1, 2, 3, 5, 10, 13, 16, 17, 18, 31, 39, 41, 44, 45, 52, 53, 55, 59, 62, 63, 67, 73, 78, 79, 81, 82, 84, 87, 88, 91, 98, 99], 84: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 85: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 86: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 87: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 88: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 89: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 90: [0, 7, 11, 12, 13, 19, 27, 28, 29, 30, 32, 33, 36, 39, 43, 46, 49, 51, 57, 58, 60, 61, 62, 65, 72, 74, 75, 77, 80, 81, 87, 90, 92, 93, 95, 96, 97], 91: [0, 7, 11, 12, 1

In [ ]:
# if __name__ == "__main__":
#     threshold = 5 # patient survival time must be >= 5
#     compat = {
#     "O":["O"],
#     "A":["O","A"],
#     "B":["O", "B"],
#     "AB":["O", "A", "B", "AB"],
#     }
#     adj = {}
#     surv = {}
#     for j in range(n_pairs): # index for donor's pair
#         adj[j] = [] # start with an empty list for each donor
#         for i in range(n_pairs): # index for patient's pair
#             if don_btype[j] in compat[pat_btype[i]]: # 'j' is blood-type compatible with 'i'
#                 X = [list(Xdon[j]) + list(Xpat[i])]
#                 survival = round(model.predict(X)[0],0) # predicted survival time
#                 if survival >= threshold: #
#                     adj[j].append(i)
#                     surv[j,i] = survival

        
#     cycles = get_all_cycles(adj,3)
    
#     weights = [compute_cycle_weight(c, surv) for c in cycles]
#     z, sol = kep_cycle(adj, cycles, weights)

#     print("Max total survival time:", z)
#     for s in sol:
#       print("Cycle:", s)

Gurobi 12.0.1:Gurobi 12.0.1: optimal solution; objective 1132
244 simplex iterations
1 branching node
Max total survival time: 1132.0
Cycle: (36, 84)
Cycle: (5, 63)
Cycle: (31, 34)
Cycle: (61, 70)
Cycle: (33, 93)
Cycle: (40, 99)
Cycle: (11, 49)
Cycle: (2, 75)
Cycle: (69, 73)
Cycle: (6, 7)
Cycle: (15, 46)
Cycle: (74, 86)
Cycle: (56, 68)
Cycle: (32, 79)
Cycle: (48, 72)
Cycle: (20, 62)
Cycle: (35, 41)
Cycle: (85, 87)
Cycle: (28, 60)
Cycle: (1, 83)
Cycle: (16, 76)
Cycle: (58, 90)
Cycle: (17, 43)
Cycle: (47, 65)
Cycle: (22, 88)
Cycle: (37, 38)
Cycle: (24, 94)
Cycle: (3, 12)
Cycle: (39, 55)
Cycle: (13, 42)
Cycle: (14, 89)
Cycle: (59, 97)
Cycle: (52, 57)
Cycle: (67, 78)
Cycle: (10, 30)
Cycle: (25, 98)
Cycle: (21, 82)
Cycle: (19, 26)
Cycle: (50, 92)
Cycle: (23, 64)
Cycle: (91, 96)
Cycle: (4, 54)
Cycle: (8, 29)
Cycle: (44, 80)
Cycle: (18, 27)
Cycle: (66, 81)
Cycle: (77, 95)

In [ ]:
# internal_survivals = []
# don_btype = pool[[8]].values.ravel()
# pat_btype = pool[[15]].values.ravel()
# n_pairs = len(pool)
# for i in range(n_pairs):
#   X = [list(Xdon[i]) + list(Xpat[i])]
#   survival = model.predict(X)[0]
#   internal_survivals.append(survival)

In [ ]:
# def get_all_cycles(adj:dict,K):
#     cycles = set()
#     for i in list(adj.keys()):
#         if i in adj[i]:
#             cycles.add(tuple([i,]))
#     if K>1:
#         tovisit = set(adj.keys())        
#         for i in tovisit:
#             tmpvisit = set(tovisit)
#             tmpvisit.remove(i)
#             first = i
#             all_cycles(cycles,[],first,tmpvisit,adj,K)
#     return cycles